name: flutter web Hosting
on: push

jobs:
  widgetbook-cloud-hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2

        with:
          flutter-version: '3.7.10'


      - name: Bootstrap App
        run: |
            flutter pub get


      - name: Build web
        run: |
            flutter pub get
            flutter build web --release --base-href="/widgetbook_simple/"

#      # 部署到 GitHub Pages
#      - name: Deploy to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: gh-pages # 部署到 gh-pages 分支
#          folder: build/web # 构建文件存放的位置
#          token: ${{ secrets.GH_TOKEN }}  # 使用自定义的 PAT


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'Yunbowu'
          user_email: 'yuboow@163.com'
          commit_message: 'Publish to gh-pages'